todotrain/urls.py
from django.contrib import admin
from django.urls import path
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    # Todos
    path('', views.home, name='home'),
    path('create/', views.createtodo, name='createtodo'),
    path('current/', views.currenttodos, name='currenttodos'),
    path('completed/', views.completedtodos, name='completedtodos'),
    path('todo/<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/edit', views.edittodo, name='edittodo'),
    path('todo/<int:todo_pk>/complete', views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', views.deletetodo, name='deletetodo'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True,)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import TodoForm
from .models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'todo/home.html')


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'todo/signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'todo/signupuser.html', {'form': UserCreationForm(),
                                                                'error': 'Пользователь с этим именем уже зарегистрирован'})
        else:
            return render(request, 'todo/signupuser.html', {'form': UserCreationForm(),
                                                            'error': 'Пароль не совпадал'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form': AuthenticationForm(),
                                                           'error': 'Неверное имя пользователя или пароль'})
        else:
            login(request, user)
            return redirect('currenttodos')


@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form': TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('currenttodos')
        except ValueError:
            return render(request, 'todo/createtodo.html', {'form': TodoForm(), 'error': 'Переданы некорректные данные'})


@login_required
def currenttodos(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=True)
    return render(request, 'todo/currenttodos.html', {'todos': todos})


@login_required
def completedtodos(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'todo/completedtodos.html', {'todos': todos})


@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo': todo})
    else:
        form = TodoForm(request.POST, instance=todo)
        try:
            form.save()
            return redirect('currenttodos')
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo': todo})


@login_required
def edittodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request, 'todo/edittodo.html', {'todo': todo, 'form': form})
    else:
        form = TodoForm(request.POST, instance=todo)
        try:
            form.save()
            return render(request, 'todo/viewtodo.html', {'todo': todo})
        except ValueError:
            return render(request, 'todo/edittodo.html', {'todo': todo,
                                                          'form': form,
                                                          'error': 'Переданы неверые данные'})


@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('currenttodos')


@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('currenttodos')

todo/templates/todo/base.html
<!DOCTYPE html>
<html>
	<head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% load static %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-light navbar-expand" style="background-color: red">
                <a href="{% url 'home' %}">
                    <img src="{% static 'todo/Logo-train.png' %}" style="max-height: 40px;" alt="">
                </a>
                <div class="navbar-brand">
                    <a href="{% url 'home' %}" class="nav-link">
                        <span class="text-light">Too Doo LIST</span>
                    </a>
                </div>
                {% if user.is_authenticated %}
                    <div class="navbar-collapse collapse">
                        <ul class="navbar-nav mr-auto">
                            <li>
                                <a class="nav-link text-light" href="{% url 'createtodo' %}">Создать</a>
                            </li>
                            <li>
                                <a class="nav-link text-light" href="{% url 'currenttodos' %}">Активные</a>
                            </li>
                            <li>
                                <a class="nav-link text-light" href="{% url 'completedtodos' %}">Завершенные</a>
                            </li>
                        </ul>
                    </div>
                    <div class="" >
                        <form action="{% url 'logoutuser' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-dark text-light">{{ user.username }} | ВЫХОД</button>
                        </form>
                    </div>
                {% else %}
                    <div class="navbar-collapse collapse"></div>
                    <div>
                        <ul class="navbar-nav mr-auto">
                            <li>
                                <a class="nav-link text-light" href="{% url 'loginuser' %}">Вход</a>
                            </li>
                            <li>
                                <a class="nav-link text-light" href="{% url 'signupuser' %}">Регистрация</a>
                            </li>
                        </ul>
                    </div>
                {%  endif %}
            </nav>
        </header>
        <main class="row">
            <div class="vw-50 mx-auto">
                {% block content %}
                {% endblock %}
            </div>
        </main>
    </body>
</html>

todo/templates/todo/completedtodos.html
{%  extends 'todo/base.html' %}

{% block content %}

    <div class="text-center">
        <h1 style="color: red">Завершенные задачи</h1>
    </div>

    <div style="width: 500px;">
        <ul class="list-group">
            {% for todo in todos %}
                <li class="list-group-item">
                    <div style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        <a href="{% url 'viewtodo' todo.id %}">
                            <span class="h5 text-danger">
                                {{ todo.title }}
                            </span>
                        </a>
                    </div>
                    <div style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        <span>
                            {{ todo.memo }}
                        </span>
                    </div>
                    <div style="display: inline-flex; position: absolute; top: 0px; right: 0px">
                        <span class="badge badge-secondary " style="background-color: red">{{ todo.datecompleted }}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

todo/templates/todo/createtodo.html
{%  extends 'todo/base.html' %}

{% block content %}
    <div class="text-center">
        <h1>Создать</h1>

        <h2>{{ error }}</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group ">
                    {% if field.label == "Title" %}
                        <label for="id_title">Название:</label>
                        <div>{{ field }}</div>
                    {% elif field.label == "Memo" %}
                        <label for="id_memo">Описание:</label>
                        <div>{{ field }}</div>
                    {% elif field.label == "Important" %}
                        <label for="id_important">Важно:</label>
                        {{ field }}
                    {% endif %}
                </div>
            {% endfor %}
            <button class="btn btn-outline-dark" type="submit">Создать</button>
        </form>
    </div>

{% endblock %}

todo/templates/todo/currenttodos.html
{%  extends 'todo/base.html' %}

{% block content %}
    <div class="text-center">
        <h1 style="color: red">Активные задачи</h1>
    </div>
    <div style="width: 500px;">
        <ul class="list-group">
            {% for todo in todos %}
                <li class="list-group-item">
                    <div style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        <a href="{% url 'viewtodo' todo.id %}">
                            <span class="h5 text-danger">
                                {{ todo.title }}
                            </span>
                        </a>
                    </div>
                    <div style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        <span>
                            {{ todo.memo }}
                        </span>
                    </div>
                    {% if todo.important %}
                        <div style="display: inline-flex; position: absolute; top: 0px; right: 0px">
                            <span class="badge badge-danger " style="background-color: red">Важно</span>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

todo/templates/todo/edittodo.html
{%  extends 'todo/base.html' %}

{% block content %}
    <div class="text-center">
        <h1>Редактировать</h1>

        <h2>{{ error }}</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {% if field.label == "Title" %}
                        <label for="id_title">Название:</label>
                        <div>{{ field }}</div>
                    {% elif field.label == "Memo" %}
                        <label for="id_memo">Описание:</label>
                        <div>{{ field }}</div>
                    {% elif field.label == "Important" %}
                        <label for="id_important">Важно:</label>
                        {{ field }}
                    {% endif %}
                </div>
            {% endfor %}
            <button class="btn btn-outline-dark" type="submit">Сохранить</button>
        </form>
    </div>

{% endblock %}

todo/templates/todo/home.html
{%  extends 'todo/base.html' %}

{% block content %}

This home page

{% endblock %}

todo/templates/todo/loginuser.html
{%  extends 'todo/base.html' %}

{% block content %}
    <div class="text-center">
        <h1>Авторизация</h1>

        <div>
            <span style="color: red">{{ error }}</span>
        </div>

        <form method="post">
            {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {% if field.label == "Username" %}
                            <label for="id_username">Пользовательское имя:</label>
                        {% elif field.label == "Password" %}
                            <label for="id_password">Пароль:</label>
                        {% endif %}
                        <div>
                            {{field}}
                        </div>
                    </div>
                {% endfor %}
            <button class="btn btn-outline-dark" type="submit">Войти</button>
        </form>
    </div>

{% endblock %}

todo/templates/todo/signupuser.html
{%  extends 'todo/base.html' %}

{% block content %}

    <div class="text-center">
        <h1>Регистрация</h1>

        <div>
            <span style="color: red">{{ error }}</span>
        </div>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {% if field.label == "Username" %}
                        <label for="id_username">Пользовательское имя:</label>
                    {% elif field.label == "Password" %}
                        <label for="id_username">Пароль:</label>
                    {% elif field.label == "Password confirmation" %}
                        <label for="id_username">Подтверждение пароля:</label>
                    {% endif %}
                    <div>
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-outline-dark" type="submit">Зарегистрировать</button>
        </form>
    </div>

{% endblock %}

todo/templates/todo/viewtodo.html
{%  extends 'todo/base.html' %}

{% block content %}

    <div class="" style="width: 500px">
        <div class="">
            <div class="card" style="margin-top: 20px">
                <div class="card-header container-fluid">
                    <div class="text-center" style=" text-align: center;">
                        <span class="h4">
                            {{ todo.title }}
                        </span>
                    </div>
                    {% if todo.important %}
                        <div style="display: inline-flex; position: absolute; top: 0px; right: 0px">
                            <span class="badge badge-danger " style="background-color: red">Важно</span>
                        </div>
                    {% endif %}
                </div>
                <div class="card-body">
                    <span>{{ todo.memo }}</span>
                </div>
                <div class="card-footer">
                    <span>{{ todo.created }}</span>
                    {% if todo.datecompleted %}
                        <span style="color: #28a745"> - {{ todo.datecompleted }}</span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div style="margin-top: 20px; width: 500px;">
        <div class="row">
            <div class="col-2">
                <form method="post" action="{% url 'deletetodo' todo.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger" style="background-color: red" type="submit">Удалить</button>
                </form>
            </div>
            {% if not todo.datecompleted %}
                <div class="col-7">
                    <form method="get" action="{% url 'edittodo' todo.id %}">
                        {% csrf_token %}
                        <button class="btn btn-dark" type="submit">Редактировать</button>
                    </form>
                </div>
                <div class="col-1">
                    <form method="post" action="{% url 'completetodo' todo.id %}">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit">Завершить</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}